---
- hosts: localhost
  tasks:
    - name: Vagrant status
      vagrant:
        dest: /home/student/cm/ansible/day-4/
        state: started
      register: hostinfo


    - name: Add discovered hosts
      add_host:
        groups: vagrant
        name: "{{ hostinfo.os_name }}"
        hostname: "{{ hostinfo.os_name }}"
        ansible_host: "{{ hostinfo.ip }}"
        ansible_port: "{{ hostinfo.port }}"
        ansible_connection: ssh
        ansible_user: "{{ hostinfo.user }}"
        ansible_ssh_private_key_file: "{{ hostinfo.key }}"
      when: hostinfo.status == "running"

- name: Tomcat getting ready for deployment
  hosts: vagrant
  become: yes
  become_method: sudo
  roles:
  - java
  - tomcat
  - nginx
  roles:
  - deploy
  tags: deploy_app
